name: Publish To Wordpress

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          mkdir tmp-svn
          cd tmp-svn
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}}
          cp -fR ../wp-plugin/* .
          svn add * --force
          svn update * --accept mine-full
          svn resolve . --accept working -R
          svn commit -m"${{github.event.release.name}}: ${{github.event.release.body}}" --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}}
