name: Publish To Wordpress

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          sudo chmod -R 775 wp-plugin
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}} --depth immediates tmp-svn
          cd tmp-svn
          svn update --set-depth infinity assets
          svn update --set-depth infinity trunk
          cp -Rf ../wp-plugin/assets/* ./assets
          cp -Rf ../wp-plugin/trunk/* ./trunk
          svn add --force *
          svn resolve . --accept mine-full -R
          svn update --accept mine-full
