name: Publish To Wordpress

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          sudo chmod -R 775 wp-plugin
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}} wp-plugin --depth empty
          svn add --force wp-plugin/*
          svn resolve wp-plugin --accept working -R
