name: Publish To Wordpress

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          sudo chmod -R 775 wp-plugin
          cd wp-plugin
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}} . --depth empty
          svn add --force *
          svn resolve . --accept mine-full -R
          svn update
          svn commit . -m"${{github.event.release.name}}: ${{github.event.release.body}}" --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}}
